### ISSUE TITLE
~~What flavour of regex is being used ?~~ README: add info about using escape character in regexes

### ISSUE THREAD

**Issue by jrfnl** [srvaroa/labeler#105]
~~... and where can I find the documentation of the supported syntaxes for this regex flavour ?~~

~~It would be good if a link to that documentation could be added to the README.~~

---

The problem I was trying to solve is as follows:

In a PR template there is a block like this:
```md
## Types of changes
<!-- What types of changes does your code introduce? Put an `x` in all the boxes that apply: -->
- [ ] Bug fix _(non-breaking change which fixes an issue)_
- [ ] New feature _(non-breaking change which adds functionality)_
- [ ] Breaking change _(fix or feature that would cause existing functionality to change)_
    - [ ] This change is only breaking for integrators, not for external standards or end-users.
- [ ] Documentation improvement
```

... which means that if people fill out the template correctly, the PR will have an `[x]` for one of these, like so:
```md
- [x] Bug fix _(non-breaking change which fixes an issue)_
```

I'm trying to attach a label to a PR based on this, so I have a section in `labeler.yml` which looks like this:
```yml
- label: "Type: bug"
  body: "x\] Bug fix"
- label: "Type: enhancement"
  body: "x\] New feature"
```

As you can see I'm slash-escaping the `]` character as it is (normally) a special character in regex.

When that workflow runs though, it silently fails with the following error (where line 79 is one of the `body:...` lines):
```
2023/11/10 18:19:14 Unable to unmarshall config yaml: line 79: found unknown escape character: 
2023/11/10 18:19:14 Unable to unmarshall legacy config: yaml: line 79: found unknown escape character
2023/11/10 18:19:14 Unable to unmarshall legacy config yaml: line 79: found unknown escape character: 
2023/11/10 18:19:14 Unable to parse configuration
```

What makes this extra awkward is that testing the workflow is difficult as I set it up to only run on `pull_request_target` (and only when a PR is opened), which meant that the workflow run for the PR which made the change to the `labeler.yml` file ran without issues as it was using the _previous_ version of the `labeler.yml` file, meaning I only noticed the problem when the _next_ PR was opened.

I tried adding `fail_on_error: true`, but that gave me an `Warning: Unexpected input(s) 'fail_on_error', valid inputs are ['entryPoint', 'args', 'config_path', 'use_local_config']` error.

And even if it had worked, adding `fail_on_error: true` wouldn't have changed anything as in that case, it would still have been the _next_ PR on which the workflow run would have failed.

Adding something like the below (with config for yamllint) would probably have caught it, but it is a bit roundabout that I need an extra job to make sure changes to the set up of _this_ job will work.
```yml
  yamllint:
    name: 'Lint Yaml'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Yamllint on all yaml files in repo
        run: yamllint . --format colored --strict

      - name: Pipe Yamllint results on to GH for inline display
        if: ${{ failure() }}
        run: yamllint . --format github --strict
```

Either way, a couple of hours of debugging has led me to a solution: use single quotes for those regexes instead of double quotes. It wasn't so much a regex issue, but actually a Yaml issue, where Yaml would get confused by the escaping.

---

Either way, even though I solved my own issue by now, I'm going to open this issue anyway for two reasons:
1. I'm hoping this write-up might help to improve the README further.
2. So that others may find a solution more easily than I did ;-)

**Comment by srvaroa** [comment]
Hi @jrfnl thanks for taking the time to troubleshoot and report in detail! This has several separate points so let me take them individually:

> What makes this extra awkward is that testing the workflow is difficult as I set it up to only run on pull_request_target (and only when a PR is opened), which meant that the workflow run for the PR which made the change to the labeler.yml file ran without issues as it was using the previous version of the labeler.yml file, meaning I only noticed the problem when the next PR was opened.

Having the execution in a PR take the labeler.yml config from the main branch instead of the PRs's is the intended default behaviour, but there was not a strong rationale for that. Originally I reasoned that a maintainer would prefer to avoid a situation where a PR contributor changes labelling logic which affects how the PR is reviewed. There are good reasons for choosing the opposite behaviour though. 

`use_local_config` was introduced to give the user choice over that behaviour. When that option is set to true, the action will use the _local_ labeler.yml from the PRs's checkout. The default is false for backwards compatibility reasons so you'll have to enable it. Let me know if that gives you the expected behaviour.

> I tried adding fail_on_error: true, but that gave me an Warning: Unexpected input(s) 'fail_on_error', valid inputs are ['entryPoint', 'args', 'config_path', 'use_local_config'] error.

Yes, this is a bug, I introduced this very recently to the action binary, but forgot to add it to the action's inputs. I'll fix this now.

Finally, you're right that cases like the broken configuration are hard to spot. Apart of documenting the regex flavour in the README, I have been wanting to improve the quality of logs. I'll do both as part of this issue.

Thanks again for the feedback!

**Comment by srvaroa** [comment]
README fixed here: https://github.com/srvaroa/labeler/pull/109

I'll close this and make a separate pass improving the logs and overall error output. Thanks again for the feedback and taking the time to troubleshoot!

**Comment by jrfnl** [comment]
@srvaroa 

> > What makes this extra awkward is that testing the workflow is difficult as I set it up to only run on pull_request_target (and only when a PR is opened), which meant that the workflow run for the PR which made the change to the labeler.yml file ran without issues as it was using the previous version of the labeler.yml file, meaning I only noticed the problem when the next PR was opened.
> 
> Having the execution in a PR take the labeler.yml config from the main branch instead of the PRs's is the intended default behaviour, but there was not a strong rationale for that. Originally I reasoned that a maintainer would prefer to avoid a situation where a PR contributor changes labelling logic which affects how the PR is reviewed. There are good reasons for choosing the opposite behaviour though.

To be honest, I think using the `default` branch as the standard, makes perfect sense from a security perspective.

A lot of repos use labels to tag things which can automatically be merged once the CI builds pass. Allowing the PR local version of the `labeler.yml` file to decide on the labels to add would allow for a malicious actor to craft a PR which will add a security vulnerability and would then be automatically merged based on something the malicious actor changed in the `labeler.yml` file in the same PR.

I opted to use the `pull_request_target` event for running this action exactly for that reason (that always uses the `default` branch).

> `use_local_config` was introduced to give the user choice over that behaviour. When that option is set to true, the action will use the _local_ labeler.yml from the PRs's checkout. The default is false for backwards compatibility reasons so you'll have to enable it. Let me know if that gives you the expected behaviour.

I used that during debugging, but what I was struggling with is basically to find a way to a) have things secure, but b) also have a way to validate that PRs which introduce changes to the `labeler.yml` don't result in a silently failing action.

This is the workflow I've now ended up with/decided upon:

```yml
name: Label new PRs

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_target
  # The `pull_request_target` event is used for "normal" PRs to label them when they are opened.
  # This will use the `labeler.yml` file in the default (main) branch of the repo.
  pull_request_target:
    types:
      - opened
      - ready_for_review

  # The `pull_request` event is used for PRs which change the files which handle the labeling to prevent a silently failing action.
  # This will use the `labeler.yml` file in the PR branch.
  pull_request:
    paths:
      - '.github/workflows/label-new-prs.yml'
      - '.github/labeler.yml'

jobs:
  label-new-prs:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'OrgName' && github.event_name == 'pull_request_target'

    name: Add labels to new PRs

    steps:
      - uses: srvaroa/labeler@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

  validate-labeler-worflow:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'OrgName' && github.event_name == 'pull_request' && github.event.pull_request.merged == false

    name: Validate changes to Labeler logic

    steps:
      # Checkout is needed to use the `use_local_config` option.
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: srvaroa/labeler@master
        with:
          use_local_config: true
          fail_on_error: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

I can imagine this could also be useful for others ?


> Finally, you're right that cases like the broken configuration are hard to spot. Apart of documenting the regex flavour in the README, I have been wanting to improve the quality of logs. I'll do both as part of this issue.

Awesome! and thank you for being so responsive!
