### ISSUE TITLE
`fail_on_error: true` doesn't seem to work

### ISSUE THREAD

**Issue by jrfnl** [srvaroa/labeler#106]
As mentioned in passing in #105 :

> I tried adding `fail_on_error: true`, but that gave me an `Warning: Unexpected input(s) 'fail_on_error', valid inputs are ['entryPoint', 'args', 'config_path', 'use_local_config']` error.

The workflow I used while debugging the issue looked like this:
```yml
jobs:
  label-new-prs:
    runs-on: ubuntu-latest

    steps:
      # Checkout is needed to use the `use_local_config` option.
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: srvaroa/labeler@master
        with:
          use_local_config: true
          fail_on_error: true
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
```

Also note my comment about the need for `checkout` when using the `use_local_config` option. That might be something to mention in the README.
