### ISSUE TITLE
Enhanced label customization

### ISSUE THREAD

**Issue by paduszyk** [srvaroa/labeler#121]
Hi!

Have you ever considered extending label customization? For instance, one could define (in `labeler.yml`) a color and/or description of the labels when applying the rules.

```yaml
labels:
- label: "🔧 chore"
  color: "202020"
  description: "Configuration, codebase maintenance tools"
  files:
    - '\.editorconfig'
    - '\.gitignore'
```

Thanks!

By the way: Thanks for developing and maintaining the action! It's great! 🙇🏻 👍🏻
