### ISSUE TITLE
author-can-merge: false does not seem to work

### ISSUE THREAD

**Issue by jrfnl** [srvaroa/labeler#123]
Hiya,

As one of the criteria in a `labeler.yml` file, I have the following:
``` yml
 labels:
   - label: "Status: triage"
     draft: false
     author-can-merge: false
```

### I'd expect

The `Status: triage` label to be added to all non-draft PRs where the author doesn't have commit rights in the repo.

### What actually happened

The `Status: triage` label does not get added to PRs from outside contributors (who don't have commit rights to the repo).

### Other info

I haven't tested yet if it works when I set it as follows, but if it does, I'd still find that counter-intuitive, as I'd expect `author-can-merge: false` to be respected.

```yml
labels:
  - label: "Status: triage"
    negate: true
    draft: false
    author-can-merge: true
```
