### ISSUE TITLE
Body filtering

### ISSUE THREAD

**Issue by Caellian** [srvaroa/labeler#156]
I'd like to use this for labeling issues in Conky, but as part of issue reports people often paste their configuration files which contain keywords I'd like to check for. This means that checking a lot of labels in the body would yield a lot of false positives.

<details>
<summary>Example:</summary>

#### Description

Some issue that mentions HW **sensors** not working. Therefore the issue should only be labeled with `sensors` label.

#### Config
```lua
conky.text = [[
  HDD: ${hdd_variable} -- HDD is detected and issue labeled `disk io`
  Volume: ${volume_variable} -- Volume is detected and issue labeled `audio`
]]
```

</details>

Not the best or most accurate example, but I hope it gets the point across, based on contents of that code block the `body` could trigger all labels.

I suggest adding a mechanism that allows excluding parts of MD content from regex, either by checking only content under a specific title (e.g. Details/Description) or by excluding code blocks (might be easier to implement (remove all "\`\`\`(\w+)?.+\`\`\`")).

**Comment by srvaroa** [comment]
Hi, sorry I forgot to reply on this one. This makes sense, I have to experiment a bit with something similar to your suggestion. I can see something like:

- body:
  pre-filter: <remove-all-regex>
  filter: <actual matching regex>

**Comment by Caellian** [comment]
Thanks for the reply.

I think that simple title-based filtering might be a good addition to `pre-filter` down the line. It's commonly much simpler to exclude/include everything in section than it would be to write a regex that removes stuff. This is less clear from the example because `\[\[.*?\]\]` works in this case perfectly, but there's cases where removed content can only be differentiated based on location because it's structurally the same:

<details>
<summary><h3>Example</h3></summary>

<h4>Description</h4>

\[...\]

I believe same might be the case with  **Ubuntu**, but I don't have it installed so that needs confirmation. Also, **Void Linux** doesn't use systemd so that's very likely also the case there.

<h4>System</h4>

OS: Linux
Distro: **Arch Linux**


</details>

The most sane way of dealing with this using regex would be to remove `.*## System`, but it feels more faulty than being able to extract sections.

Go has a crate for markdown, but I think this would be more complicated than simply splitting input on lines that start with `#{1,6}` and internally producing something like:
```yml
sections:
  - level: 3
    title: <title>
    body: <content>
```

Filtering can then use:
```yml
- body:
  - title:
      - content: <title name regex>
        level: <title level number>
      - content: <title name regex>
        level: <title level number>
    label: <label name>

# Probably requires restructuring
- body:
  - section:
      - title: <title name regex>
        <any body items except section>
    label: <label name>
```

If both get added, I suggest `pre-filter` to run after that.
