### ISSUE TITLE
Support for GitHub Enterprise Server

### ISSUE THREAD

**Issue by posquit0** [srvaroa/labeler#34]
When I tried to use `srvaroa/labeler` action in GitHub Server, I got the error message like below.

```
GET https://api.github.com/repos/${my-org}/${my-repo}/contents/.github/labeler.yaml?ref=xxxxxxxxxxx: 401 Bad credentials []
```
I think that configuration for GITHUB_API_HOST is need to support GitHub Enterprise Server.

**Comment by srvaroa** [comment]
@posquit0 I have just pushed a branch that might work for this. Unfortunately I don't have access to a private server so I'd appreciate if you can help test it if you're still interested.

https://github.com/srvaroa/labeler/tree/enterprise

Thanks

**Comment by jdtechnology** [comment]
Hi @srvaroa I have tested this on an enterprise server against this commit and can confirm that it does work, very nice work 👍 

Here is the step I have added to the job:

```yaml
    steps:
      - name: Set GHE_HOST
        run: |
          echo "GITHUB_API_HOST=${GITHUB_SERVER_URL}/" >> $GITHUB_ENV
```
Thank you
