### ISSUE TITLE
Negative lookahead is not supported

### ISSUE THREAD

**Issue by Robin-Hoodie** [srvaroa/labeler#46]
Logs from GH action:

```bash
2022/07/26 13:26:48 Matching `^fix\(.*\)[^!]((?!BREAKING\sCHANGE).)*$` against: `fix(.github/labeler.yml): labels not being applied correctly [CDS-000]`
2022/07/26 13:26:48 release-as-fix: condition Title matches regex yields false
```

Label config

```yml
version: 1
labels:
  // Other labels
  - label: 'release-as-fix'
    title: '^fix\(.*\)[^!]((?!BREAKING\sCHANGE).)*$'
```

- Regex that should match `^fix\(.*\)[^!]((?!BREAKING\sCHANGE).)*$`
- PR title `fix(.github/labeler.yml): labels not being applied correctly [CDS-000]`

If using a tool like https://regex101.com/ , you can verify that the PR title should match the regex

**Comment by srvaroa** [comment]
Hi, thanks for reporting this. It looks like a limitation in the go regex package:

![image](https://user-images.githubusercontent.com/346110/181019233-ce6adc7f-a1ed-4ef2-84cf-87eca12794b1.png)

It chokes on the negative look ahead. Removing the `!?` makes the expression compile. A quick search in Stack Overflow [seems to confirm it](https://stackoverflow.com/questions/26771592/negative-look-ahead-in-go-regular-expressions).

Is there a chance you can rewrite the expression without using it? I can look into using a different regex library but that might take me a bit longer.

Cheers,

**Comment by Robin-Hoodie** [comment]
@srvaroa I've taken a look at working around this, but couldn't find any other way to do this w/ a regex.

The reason I'm using the negative lookahead is is because we have another label, `release-as-major` that's applied in case the PR title does contain "BREAKING CHANGE" and I don't want both "release-as-fix" and "release-as-major" to be applied.

```yml
- label: 'release-as-fix'
  title: '^fix\(.*\)((?!BREAKING\sCHANGE).)*'

- label: 'release-as-major'
  title: '^.*BREAKING CHANGE'
```

An alternative would be if it'd be possible to conditionally prevent a label from being applied if another label is already being applied.

A hypothetical API could look like this

```yml
- label: 'release-as-fix'
  title: '^fix.*$'
  not-together-with: '^release-as-major$'

- label: 'release-as-major'
  title: '^.*BREAKING CHANGE'
```

I'm open for other suggestions 🙂
